<?php

namespace Database\Seeders;

use App\Models\Event;
use App\Models\EventImage;
use Illuminate\Database\Seeder;

class EventSeeder extends Seeder
{
    public function run(): void
    {
        $eventos = [
            [
                'title' => 'OUTSIDER x INSOMNIO I',
                'description' => "OUTSIDER X @club1nsomnio # FASHION SHOW ₊ ⊹𖦏♱༺༒︎⊰‿̩͙||BANNER POR @kirakira.films | FOTOS POR @erreph_ @kontra_productivo @roblab.photo @foto.fractal01 @sweetcottonn_ @ooldestdreamm @rosa.mexic4no @luis_stuner @stra.voss @juuniink @muela_del_juici0 @arath_cg1",
                'date' => '2026-05-07',
                'location' => 'Club 1nsomnio, FNSM',
                'banner_path' => 'https://i.postimg.cc/tgNR1SCc/kirakirafilms1.gif',
                'images' => [
                    // MANTENIDOS: @erreph__ (26) y @kontra_productivo (7)
                    'https://i.postimg.cc/QVZx9R55/erreph-1.webp', 'https://i.postimg.cc/kDPX6k8s/erreph-10.jpg', 'https://i.postimg.cc/G9nh8ZYq/erreph-11.jpg', 'https://i.postimg.cc/YjBqGJgd/erreph-12.webp', 'https://i.postimg.cc/9zHFRvT8/erreph-13.jpg', 'https://i.postimg.cc/rz2F0vWY/erreph-14.jpg', 'https://i.postimg.cc/QVZx9R5z/erreph-15.jpg', 'https://i.postimg.cc/RhHZ0M3t/erreph-16.jpg', 'https://i.postimg.cc/j27SjsWN/erreph-17.jpg', 'https://i.postimg.cc/6qvpQ97n/erreph-18.jpg', 'https://i.postimg.cc/x8z1d0kL/erreph-19.jpg', 'https://i.postimg.cc/9zHFRvTZ/erreph-2.webp', 'https://i.postimg.cc/Znd5qT9r/erreph-20.jpg', 'https://i.postimg.cc/L518sHqB/erreph-21.jpg', 'https://i.postimg.cc/907QfW4Y/erreph-22.jpg', 'https://i.postimg.cc/mkHgrbcS/erreph-23.webp', 'https://i.postimg.cc/KjM8YZKf/erreph-24.webp', 'https://i.postimg.cc/w3YTySJm/erreph-25.webp', 'https://i.postimg.cc/1415nL6F/erreph-26.webp', 'https://i.postimg.cc/mhW2z0M7/erreph-3.jpg', 'https://i.postimg.cc/vDwHgp9W/erreph-4.jpg', 'https://i.postimg.cc/4nRN7rt6/erreph-5.jpg', 'https://i.postimg.cc/YjBqGJgN/erreph-6.jpg', 'https://i.postimg.cc/0r12MLm0/erreph-7.jpg', 'https://i.postimg.cc/t7GCZLPz/erreph-8.jpg', 'https://i.postimg.cc/QVZx9R5b/erreph-9.jpg',
                    'https://i.postimg.cc/SsdVTMmy/kontra-productivo2.webp', 'https://i.postimg.cc/vBhXqVGb/kontra-productivo4.webp', 'https://i.postimg.cc/3R19Sv37/kontra-productivo5.webp', 'https://i.postimg.cc/W38SWks1/kontra-productivo6.webp', 'https://i.postimg.cc/KzfQqMmG/kontra-productivo7.webp', 'https://i.postimg.cc/Hxz3ZyTL/kontra-productivo8.webp', 'https://i.postimg.cc/mDjVXHTD/kontra-productivo9.webp',
                    // AGREGADOS PARA EQUILIBRAR:
                    'https://i.postimg.cc/Qx2gqbc6/roblab-photo10.webp', 'https://i.postimg.cc/jdp6hXy3/roblab-photo11.webp', 'https://i.postimg.cc/L8jtQ1Vt/roblab-photo12.webp', 'https://i.postimg.cc/rw51Zr9G/roblab-photo13.webp', 'https://i.postimg.cc/VkXqZCFB/roblab-photo14.webp', 'https://i.postimg.cc/NjR6CHxk/roblab-photo15.webp', 'https://i.postimg.cc/t4F3vxz5/roblab-photo16.webp', 'https://i.postimg.cc/GmvFgyjK/roblab-photo17.webp', 'https://i.postimg.cc/tCKdz5F5/roblab-photo2.webp', 'https://i.postimg.cc/jdp6hXy3/roblab-photo3.webp', 'https://i.postimg.cc/ncyK1kq2/roblab-photo4.webp', 'https://i.postimg.cc/3JsjZB2Z/roblab-photo5.webp', 'https://i.postimg.cc/5Nh5m38p/roblab-photo6.webp', 'https://i.postimg.cc/3JsjZB2n/roblab-photo7.webp', 'https://i.postimg.cc/yYMhTP0L/roblab-photo8.webp', 'https://i.postimg.cc/Qx2gqbc4/roblab-photo9.webp',
                    'https://i.postimg.cc/mrbHd6kN/fotofractal0110.webp', 'https://i.postimg.cc/cJsnD5CB/fotofractal0111.webp', 'https://i.postimg.cc/XvVC2Dq8/fotofractal0112.webp', 'https://i.postimg.cc/Dz2XCY06/fotofractal0113.webp', 'https://i.postimg.cc/7LmTjMJ2/fotofractal0114.webp', 'https://i.postimg.cc/cJX8PMtf/fotofractal0115.webp', 'https://i.postimg.cc/ZqVyXFvr/fotofractal0116.webp', 'https://i.postimg.cc/jjZJBQnQ/fotofractal0117.webp', 'https://i.postimg.cc/XvQytcBk/fotofractal0118.webp', 'https://i.postimg.cc/1z9qWYXn/fotofractal012.webp', 'https://i.postimg.cc/bvzt6Fr2/fotofractal013.webp', 'https://i.postimg.cc/W42k9fzq/fotofractal014.webp', 'https://i.postimg.cc/6Q9vH1q7/fotofractal015.webp', 'https://i.postimg.cc/zfJgdPvW/fotofractal016.webp', 'https://i.postimg.cc/SKyMZtRc/fotofractal017.webp', 'https://i.postimg.cc/BvqKhwbH/fotofractal018.webp',
                    'https://i.postimg.cc/zvWwmHrB/sweetcotton-10.jpg', 'https://i.postimg.cc/3RzjbCPw/sweetcotton-2.jpg', 'https://i.postimg.cc/rm7GYCvw/sweetcotton-3.jpg', 'https://i.postimg.cc/8cWd8fSV/sweetcotton-4.jpg', 'https://i.postimg.cc/6qRVs4Xt/sweetcotton-5.jpg', 'https://i.postimg.cc/zvWwmHrq/sweetcotton-6.jpg', 'https://i.postimg.cc/WzrmRqv2/sweetcotton-7.jpg', 'https://i.postimg.cc/kG8NrRmJ/sweetcotton-8.jpg', 'https://i.postimg.cc/Y0gNcLHC/sweetcotton-9.jpg',
                    'https://i.postimg.cc/xTVj9NQQ/muela-del-juici02.jpg', 'https://i.postimg.cc/gkbcGLpm/muela-del-juici03.jpg', 'https://i.postimg.cc/MKJZzfwz/muela-del-juici04.jpg', 'https://i.postimg.cc/9FHXcw2V/muela-del-juici05.jpg', 'https://i.postimg.cc/02159KvQ/muela-del-juici06.jpg', 'https://i.postimg.cc/3Jj8Nrr8/muela-del-juici07.jpg', 'https://i.postimg.cc/wT5qMxxj/muela-del-juici08.jpg', 'https://i.postimg.cc/8Pdpckkc/muela-del-juici09.jpg',
                    'https://i.postimg.cc/dQrvNQyn/arath-cg110.jpg', 'https://i.postimg.cc/44VZ249W/arath-cg111.jpg', 'https://i.postimg.cc/c1wZk1nD/arath-cg112.jpg', 'https://i.postimg.cc/T2gGN2DN/arath-cg113.jpg', 'https://i.postimg.cc/Y2YkD2Wy/arath-cg114.jpg', 'https://i.postimg.cc/SQCq1QMP/arath-cg115.jpg', 'https://i.postimg.cc/2jhm9jZJ/arath-cg116.jpg', 'https://i.postimg.cc/nVBZSVmx/arath-cg117.jpg', 'https://i.postimg.cc/y6cBp6RH/arath-cg118.jpg', 'https://i.postimg.cc/DfLFpfG7/arath-cg119.jpg', 'https://i.postimg.cc/Y06Hv870/arath-cg12.jpg', 'https://i.postimg.cc/7P0DtPzx/arath-cg120.jpg', 'https://i.postimg.cc/ryxcZy4y/arath-cg121.jpg', 'https://i.postimg.cc/vHyyJRrJ/arath-cg122.jpg', 'https://i.postimg.cc/hPnnkF8F/arath-cg123.jpg', 'https://i.postimg.cc/28YYspdR/arath-cg124.jpg', 'https://i.postimg.cc/MKwwCk08/arath-cg125.jpg', 'https://i.postimg.cc/Yq775cNH/arath-cg126.jpg', 'https://i.postimg.cc/SN44B0Lm/arath-cg127.jpg', 'https://i.postimg.cc/X7WWRMKW/arath-cg128.jpg', 'https://i.postimg.cc/SN44B0Lx/arath-cg129.jpg', 'https://i.postimg.cc/90dhD12F/arath-cg13.jpg', 'https://i.postimg.cc/ZKmmGkPq/arath-cg130.jpg', 'https://i.postimg.cc/Nftt3h8M/arath-cg131.jpg', 'https://i.postimg.cc/ncxxy8Kr/arath-cg132.jpg', 'https://i.postimg.cc/sDzzkFP1/arath-cg133.jpg', 'https://i.postimg.cc/J488fw3G/arath-cg134.jpg', 'https://i.postimg.cc/GhRRW0P4/arath-cg135.jpg', 'https://i.postimg.cc/TYxxz8jy/arath-cg136.jpg', 'https://i.postimg.cc/kXCC0rNR/arath-cg137.jpg', 'https://i.postimg.cc/tCbbK0dW/arath-cg138.jpg', 'https://i.postimg.cc/5yBVXpJX/arath-cg14.jpg', 'https://i.postimg.cc/zvCrypNV/arath-cg15.jpg', 'https://i.postimg.cc/C5GgRJ0B/arath-cg16.jpg', 'https://i.postimg.cc/RCK9pCH7/arath-cg17.jpg', 'https://i.postimg.cc/3rm7frvj/arath-cg18.jpg', 'https://i.postimg.cc/mZCRpZHy/arath-cg19.jpg'
                ]
            ],
            [
                'title' => 'OUTSIDER x INSOMNIO II',
                'description' => "OUTSIDER X @club1nsomnio # FASHION SHOW ₊ ⊹𖦏♱༺༒︎⊰‿̩͙||BANNER POR @kirakira.films | FOTOS POR @erreph_ @kontra_productivo @roblab.photo @foto.fractal01 @sweetcottonn_ @ooldestdreamm @rosa.mexic4no @luis_stuner @stra.voss @juuniink @muela_del_juici0 @arath_cg1",
                'date' => '2026-05-07',
                'location' => 'Club 1nsomnio, FNSM',
                'banner_path' => 'https://i.postimg.cc/MpwCFyS1/Kirakirafilms-2.gif',
                'images' => [
                    // MANTENIDOS: @rosa.mexic4no (30) y @luis_stuner (46)
                    'https://i.postimg.cc/ht4CmMnM/rosamexic4no3.jpg', 'https://i.postimg.cc/3xrLG9hP/rosamexic4no10.jpg', 'https://i.postimg.cc/YC2XF8kc/rosamexic4no11.jpg', 'https://i.postimg.cc/L84yPvRK/rosamexic4no12.jpg', 'https://i.postimg.cc/t4rBNPRB/rosamexic4no13.jpg', 'https://i.postimg.cc/NjNdkTGN/rosamexic4no14.webp', 'https://i.postimg.cc/3xLtFprc/rosamexic4no15.jpg', 'https://i.postimg.cc/7ZBKn7Pc/rosamexic4no16.webp', 'https://i.postimg.cc/YCXdzg2T/rosamexic4no17.jpg', 'https://i.postimg.cc/2SH07vjP/rosamexic4no18.jpg', 'https://i.postimg.cc/K890DLc6/rosamexic4no19.jpg', 'https://i.postimg.cc/dVQWCnFj/rosamexic4no2.jpg', 'https://i.postimg.cc/52PsSvNc/rosamexic4no20.jpg', 'https://i.postimg.cc/NjNdkTft/rosamexic4no21.jpg', 'https://i.postimg.cc/Z5fwx3KZ/rosamexic4no22.jpg', 'https://i.postimg.cc/Mps9mRKW/rosamexic4no23.jpg', 'https://i.postimg.cc/4x8WQtN4/rosamexic4no24.jpg', 'https://i.postimg.cc/L8yx3f66/rosamexic4no25.webp', 'https://i.postimg.cc/g2MgHRkJ/rosamexic4no26.jpg', 'https://i.postimg.cc/13Wvr65X/rosamexic4no27.jpg', 'https://i.postimg.cc/mgdmyM2t/rosamexic4no28.jpg', 'https://i.postimg.cc/zGdxFWX3/rosamexic4no29.jpg', 'https://i.postimg.cc/t4rBNPC1/rosamexic4no30.jpg', 'https://i.postimg.cc/SKJDTsJy/rosamexic4no31.jpg', 'https://i.postimg.cc/K8c9TQbN/rosamexic4no4.jpg', 'https://i.postimg.cc/zGDdhpNd/rosamexic4no5.jpg', 'https://i.postimg.cc/0y5tSZvX/rosamexic4no6.jpg', 'https://i.postimg.cc/g2cMh4p5/rosamexic4no7.jpg', 'https://i.postimg.cc/NjGNXbtz/rosamexic4no8.jpg', 'https://i.postimg.cc/QdN67SDn/rosamexic4no9.jpg',
                    'https://i.postimg.cc/9f7ywqDx/luis-stuner10.jpg', 'https://i.postimg.cc/rpr5RtDn/luis-stuner11.jpg', 'https://i.postimg.cc/XvC9Byrz/luis-stuner12.jpg', 'https://i.postimg.cc/BvK2P1jw/luis-stuner13.jpg', 'https://i.postimg.cc/HLyb87rR/luis-stuner14.jpg', 'https://i.postimg.cc/FKL0kJYw/luis-stuner15.jpg', 'https://i.postimg.cc/q7326CN9/luis-stuner16.jpg', 'https://i.postimg.cc/1zqDVN8k/luis-stuner17.jpg', 'https://i.postimg.cc/HLyb87J1/luis-stuner18.jpg', 'https://i.postimg.cc/0Q1DY2SW/luis-stuner19.jpg', 'https://i.postimg.cc/jj7ynJDf/luis-stuner2.jpg', 'https://i.postimg.cc/KzhBPvTs/luis-stuner20.jpg', 'https://i.postimg.cc/63xnr5Zm/luis-stuner21.jpg', 'https://i.postimg.cc/85gMRPv3/luis-stuner22.jpg', 'https://i.postimg.cc/V6PnqLt2/luis-stuner23.jpg', 'https://i.postimg.cc/fLQmcTd6/luis-stuner24.jpg', 'https://i.postimg.cc/LXFLt6Pc/luis-stuner25.jpg', 'https://i.postimg.cc/0Q1DY2m1/luis-stuner26.jpg', 'https://i.postimg.cc/qRHysMnd/luis-stuner27.jpg', 'https://i.postimg.cc/9MHZdFT2/luis-stuner28.jpg', 'https://i.postimg.cc/mDWCY2ML/luis-stuner29.jpg', 'https://i.postimg.cc/cJnft8vY/luis-stuner3.jpg', 'https://i.postimg.cc/fLQmcTXW/luis-stuner30.jpg', 'https://i.postimg.cc/ZRzp8K35/luis-stuner31.jpg', 'https://i.postimg.cc/8z3hCbzc/luis-stuner32.jpg', 'https://i.postimg.cc/CxtjK4xx/luis-stuner33.jpg', 'https://i.postimg.cc/QdPpMqdV/luis-stuner34.jpg', 'https://i.postimg.cc/qvY87Gvz/luis-stuner35.jpg', 'https://i.postimg.cc/y85FNT8J/luis-stuner36.jpg', 'https://i.postimg.cc/nh5vL1h9/luis-stuner37.jpg', 'https://i.postimg.cc/bwMQvRwD/luis-stuner38.jpg', 'https://i.postimg.cc/fRFxbvR0/luis-stuner39.jpg', 'https://i.postimg.cc/MGQ1fjn1/luis-stuner4.jpg', 'https://i.postimg.cc/htw9G0tT/luis-stuner40.jpg', 'https://i.postimg.cc/YCV1SxC1/luis-stuner41.jpg', 'https://i.postimg.cc/3x6gwZxX/luis-stuner42.jpg', 'https://i.postimg.cc/t4fhgz4d/luis-stuner43.jpg', 'https://i.postimg.cc/fRFxbvRv/luis-stuner44.jpg', 'https://i.postimg.cc/XvC9ByrB/luis-stuner45.jpg', 'https://i.postimg.cc/GpyvTs4s/luis-stuner46.jpg', 'https://i.postimg.cc/Pqw1v8Cw/luis-stuner47.jpg', 'https://i.postimg.cc/wBmDRs1h/luis-stuner5.jpg', 'https://i.postimg.cc/jj7ynJDH/luis-stuner6.jpg', 'https://i.postimg.cc/jj7ynJD4/luis-stuner7.jpg', 'https://i.postimg.cc/XvC9Byrx/luis-stuner8.jpg', 'https://i.postimg.cc/q7326CNj/luis-stuner9.jpg',
                    // AGREGADOS PARA EQUILIBRAR:
                    'https://i.postimg.cc/HsgXcxmr/ooldestreamm10.webp', 'https://i.postimg.cc/Nfcm9Mt9/ooldestreamm11.jpg', 'https://i.postimg.cc/kXmK64CV/ooldestreamm12.jpg', 'https://i.postimg.cc/zDWTGhsR/ooldestreamm2.webp', 'https://i.postimg.cc/05m7ySTS/ooldestreamm3.jpg', 'https://i.postimg.cc/QN5cd72K/ooldestreamm4.jpg', 'https://i.postimg.cc/wxJDjNCm/ooldestreamm5.jpg', 'https://i.postimg.cc/J7JjzXfb/ooldestreamm6.jpg', 'https://i.postimg.cc/GhCG82R9/ooldestreamm7.jpg', 'https://i.postimg.cc/bYb1wn7x/ooldestreamm9.webp',
                    'https://i.postimg.cc/rs384z0D/stra-voss11.jpg', 'https://i.postimg.cc/Fz89S1dk/stra-voss12.jpg', 'https://i.postimg.cc/x8h0mqJm/stra-voss13.jpg', 'https://i.postimg.cc/0jF8SrMm/stra-voss14.jpg', 'https://i.postimg.cc/fypwdktY/stra-voss15.jpg', 'https://i.postimg.cc/90KW9zRZ/stra-voss16.jpg', 'https://i.postimg.cc/QCwX7V9k/stra-voss17.jpg', 'https://i.postimg.cc/1X29F4n0/stra-voss18.jpg', 'https://i.postimg.cc/RhyMtq6L/stra-voss19.jpg', 'https://i.postimg.cc/7hfHbS6T/stra-voss2.jpg', 'https://i.postimg.cc/tJwX67Zz/stra-voss20.jpg', 'https://i.postimg.cc/PJ9tDNpy/stra-voss21.jpg', 'https://i.postimg.cc/5y64j80Q/stra-voss3.jpg', 'https://i.postimg.cc/SRJSjcsM/stra-voss4.jpg', 'https://i.postimg.cc/WzhNt03Z/stra-voss5.jpg', 'https://i.postimg.cc/90rmzyMT/stra-voss6.jpg', 'https://i.postimg.cc/Vvdf5X6j/stra-voss8.jpg', 'https://i.postimg.cc/5yTxzjYy/stra-voss9.jpg',
                    'https://i.postimg.cc/s2jRv560/juuniink10.jpg', 'https://i.postimg.cc/9fmjry8k/juuniink11.jpg', 'https://i.postimg.cc/cJxNrf92/juuniink12.jpg', 'https://i.postimg.cc/FKrQ70Ww/juuniink13.jpg', 'https://i.postimg.cc/7LHyfSsp/juuniink14.jpg', 'https://i.postimg.cc/ZqbhC67G/juuniink15.jpg', 'https://i.postimg.cc/1zmZfD7P/juuniink16.jpg', 'https://i.postimg.cc/VNfcdXZL/juuniink17.jpg', 'https://i.postimg.cc/vmYdc52Z/juuniink18.jpg', 'https://i.postimg.cc/mrLGt7pr/juuniink19.jpg', 'https://i.postimg.cc/W45crtxs/juuniink2.jpg', 'https://i.postimg.cc/3w8Hd2fR/juuniink20.jpg', 'https://i.postimg.cc/0NV1mrhP/juuniink21.jpg', 'https://i.postimg.cc/KY0hL4CZ/juuniink3.jpg', 'https://i.postimg.cc/SKgb8jHS/juuniink4.jpg', 'https://i.postimg.cc/PqSnZN05/juuniink5.jpg', 'https://i.postimg.cc/1zv164bz/juuniink6.jpg', 'https://i.postimg.cc/Dzx3smR0/juuniink7.jpg', 'https://i.postimg.cc/PqXkP133/juuniink8.jpg', 'https://i.postimg.cc/PqXkP13R/juuniink9.jpg'
                ]
            ],
        ];

        foreach ($eventos as $data) {
            $imagenes = $data['images'] ?? [];
            unset($data['images']);

            $event = Event::create($data);

            foreach ($imagenes as $path) {
                EventImage::create([
                    'event_id' => $event->id,
                    'image_path' => $path
                ]);
            }
        }
    }
}